name: DS-python
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- jupyter
- numpy
- pandas>=1
- matplotlib>3
- seaborn
- pyproj
- requests
- openpyxl
- packaging
- plotly>5.3
- pip
- pip:
  - geopy > 2
